chart/madre/templates/deployment.yaml, chart/madre/values.yaml, prescricao/src/main/docker/Dockerfile, prescricao/src/main/docker/entrypoint.sh
Acrescentar Dockerfile no MS prescrição
Acrescentar MS prescrição do Chart
=> Basis 127296

internacao/pom.xml
=> Adiciona o jackson-module-jaxb-annotations como dependência no pom.xml (internação)

farmacia/src/main/resources/config/application-dev.yml, internacao/src/main/resources/config/application-dev.yml, pacientes/src/main/resources/config/application-dev.yml, prescricao/src/main/resources/config/application-dev.yml
Alteração do timeout do elasticsearch.
=> Alteração do timeout do elasticsearch.

pacientes/src/main/resources/config/liquibase/master.xml
Para correção de branch com erros
=> Organização de changelogs na master de acordo com a execução

frontend/src/app/pacientes/components/formulario-paciente/formulario-cadastro.component.html, frontend/src/app/pacientes/components/formulario-paciente/formulario-cadastro.component.ts, frontend/src/app/pacientes/components/formulario-paciente/responsavel/responsavel.component.html
Padronização de telefones em Responsável
=> Padronizando telefones na aba de responsável

frontend/src/app/internacao/formulario-unidades/components/cadastro-unidades/cadastro-unidades.component.html, frontend/src/app/internacao/formulario-unidades/models/dropwdowns/Clinica.ts, frontend/src/app/internacao/formulario-unidades/services/caracteristica.service.ts, frontend/src/app/internacao/formulario-unidades/services/clinicas.services.ts, internacao/src/main/java/br/com/basis/madre/domain/Clinica.java, internacao/src/main/java/br/com/basis/madre/service/dto/ClinicaDTO.java, internacao/src/main/resources/config/liquibase/changelog/20200713162948_changelog.xml, internacao/src/main/resources/config/liquibase/changelog/20200713164923_changelog.xml, internacao/src/main/resources/config/liquibase/master.xml, internacao/src/test/java/br/com/basis/madre/web/rest/ClinicaResourceIT.java
Como já existia uma entidade chamada Clínica, apenas acrescentei os devidos campos necessários e fiz as correções conforme o exemplo da AGHU.
=> Basis 137404

suprimentos/src/main/java/br/com/basis/suprimentos/domain/EstoqueAlmoxarifado.java, suprimentos/src/main/java/br/com/basis/suprimentos/service/dto/EstoqueAlmoxarifadoDTO.java, suprimentos/src/main/resources/config/liquibase/changelog/20200717124805_BASIS-137401.xml, suprimentos/src/main/resources/config/liquibase/master.xml
=> Adiciona novos campos que aparecem no resultado da consulta de estoque almoxarifado

frontend/src/app/pacientes/formulario/endereco/paciente-form-endereco.component.html, frontend/src/app/pacientes/formulario/endereco/paciente-form-endereco.component.ts, frontend/src/app/pacientes/formulario/telefone/paciente-form-telefone.component.html, frontend/src/app/pacientes/formulario/telefone/paciente-form-telefone.component.ts, frontend/src/app/pacientes/models/dropdowns/opcoes-de-tipo-de-endereco.ts
Como foi informado a funcionalidade está pronta, porém alguns erros em outros casos interferem na hora do cadastro, solicito nova tarefa. Grato!
=> Basis 142389

frontend/src/app/pacientes/formulario/paciente.service.ts
Correção em combo de municípios.
=> Basis 146346

frontend/src/app/pacientes/formulario/endereco/paciente-form-endereco.component.html, frontend/src/app/pacientes/formulario/endereco/paciente-form-endereco.component.ts, frontend/src/app/pacientes/formulario/paciente-form.component.html, frontend/src/app/pacientes/formulario/telefone/paciente-form-telefone.component.html, frontend/src/app/pacientes/formulario/telefone/paciente-form-telefone.component.ts
Correções em aba de endereço e telefone e inclusão de novos componentes
=> Basis 146347

frontend/src/app/pacientes/formulario/paciente.model.ts, frontend/src/app/pacientes/models/paciente-resumo.ts, pacientes/src/main/java/br/com/basis/madre/service/PacienteService.java, pacientes/src/main/java/br/com/basis/madre/service/projection/PacienteResumo.java
Incluindo numero do prontuário na tabela de pesquisa do frontend
=> Basis 161768

frontend/src/app/pacientes/formulario/paciente-list.component.html, frontend/src/app/pacientes/formulario/paciente-list.component.ts, frontend/src/app/pacientes/formulario/paciente.model.ts, frontend/src/app/pacientes/formulario/paciente.service.ts, frontend/src/app/pacientes/pacientes.service.ts, pacientes/src/main/java/br/com/basis/madre/service/PacienteService.java, pacientes/src/main/java/br/com/basis/madre/web/rest/PacienteResource.java
Incluindo busca de paciente por prontuario
=> Basis 163030

frontend/src/app/internacao/components/solicitacoes-de-internacao/solicitacoes-de-internacao.component.html, frontend/src/app/internacao/components/solicitacoes-de-internacao/solicitacoes-de-internacao.component.ts, internacao/src/main/java/br/com/basis/madre/service/SolicitacaoDeInternacaoService.java, internacao/src/main/java/br/com/basis/madre/web/rest/SolicitacaoDeInternacaoResource.java
Ajustes no back e no front para busca de internação por nome do paciente.
=> Basis 162030

prescricao/src/test/java/br/com/basis/madre/prescricao/config/WebConfigurerTest.java
Ajustando teste para passar no sonar.
=> Ajustando teste (erro do sonar)

consulta/src/main/java/br/com/basis/consulta/MadreconsultaApp.java, consulta/src/main/java/br/com/basis/consulta/config/DatabaseConfiguration.java, consulta/src/main/java/br/com/basis/consulta/domain/Emergencia.java, consulta/src/main/java/br/com/basis/consulta/service/dto/EmergenciaDTO.java, consulta/src/main/java/br/com/basis/consulta/service/projection/CalendarioResumo.java, consulta/src/main/java/br/com/basis/consulta/web/rest/vm/package-info.java
=>  Correção erro sonar  - BASIS-182765

frontend/src/app/pacientes/formulario/documentos/paciente-form-documentos.component.html
Erro de escrita no formulário de cadastro do paciente.
=> Erro de escrita - BASIS-191262

frontend/src/app/pacientes/formulario/dados-pessoais/paciente-form-dados-pessoais.component.html, internacao/src/main/java/br/com/basis/madre/repository/EventoLeitoRepository.java, internacao/src/main/java/br/com/basis/madre/repository/LeitoRepository.java, internacao/src/main/java/br/com/basis/madre/service/EventoLeitoService.java, internacao/src/main/java/br/com/basis/madre/web/rest/EventoLeitoResource.java
Soluciona o erro de liberação de leito (leito já ocupado) após liberar um leito.
=> Adicionar para apagar leito de evento_leito - BASIS-161698

pacientes/pom.xml, pacientes/src/main/docker/app.yml, pacientes/src/main/java/br/com/basis/madre/domain/Paciente.java, pacientes/src/main/java/br/com/basis/madre/service/dto/PacienteDTO.java, pacientes/src/main/java/br/com/basis/madre/service/dto/PacienteInclusaoDTO.java, pacientes/src/main/java/br/com/basis/madre/service/mapper/PacienteInclusaoMapper.java, pacientes/src/main/resources/config/application-prod.yml, pacientes/src/main/resources/config/liquibase/changelog/20210615181102_changelog.xml, pacientes/src/main/resources/config/liquibase/changelog/20210615193632_create_seq_num_prontuario.xml, pacientes/src/main/resources/config/liquibase/master.xml
Ainda está imcompleto, mas vou terminar na proxima tarefa.
=> Correção erro de cadastro - BASIS-202662

consulta/pom.xml, consulta/src/main/docker/Dockerfile, consulta/src/main/docker/postgresql.yml, consulta/src/main/java/br/com/basis/consulta/repository/EmergenciaRepository.java, consulta/src/main/java/br/com/basis/consulta/service/EmergenciaService.java, consulta/src/main/java/br/com/basis/consulta/service/ExportarEmergenciaService.java, consulta/src/main/java/br/com/basis/consulta/web/rest/EmergenciaResource.java, consulta/src/main/resources/config/application-dev.yml, consulta/src/test/java/br/com/basis/consulta/web/rest/EmergenciaResourceIT.java, frontend/src/app/consulta/components/listar-consultas/listar-consultas.component.html, frontend/src/app/consulta/components/listar-consultas/listar-consultas.component.ts, frontend/src/app/consulta/consulta.service.ts
Exportação de consultas fucionando
=> Exportar consultas emergenciais - BASIS-191264

exames/.jhipster/Exame.json, exames/.jhipster/Material.json, exames/modelo-solicitacao-exame.jdl, exames/src/main/java/br/com/basis/madre/madreexames/domain/Exame.java, exames/src/main/java/br/com/basis/madre/madreexames/domain/Material.java, exames/src/main/java/br/com/basis/madre/madreexames/service/dto/ExameDTO.java, exames/src/main/java/br/com/basis/madre/madreexames/service/dto/MaterialDTO.java, exames/src/main/resources/config/liquibase/changelog/20210705114608_added_entity_Material_Atualizado.xml, exames/src/main/resources/config/liquibase/master.xml, exames/src/test/java/br/com/basis/madre/madreexames/web/rest/ExameResourceIT.java, exames/src/test/java/br/com/basis/madre/madreexames/web/rest/MaterialResourceIT.java, frontend/src/app/app.component.ts, frontend/src/app/exames/components/cadastrar-material/cadastrar-material.component.css, frontend/src/app/exames/components/cadastrar-material/cadastrar-material.component.html, frontend/src/app/exames/components/cadastrar-material/cadastrar-material.component.ts, frontend/src/app/exames/exames.module.ts, frontend/src/app/exames/exames.routes.ts, frontend/src/app/exames/models/dropdowns/atividade.dropdown.ts, frontend/src/app/exames/models/subjects/material-de-analise.ts, frontend/src/app/exames/services/material-de-analise.service.ts
  - Entendimento da funcionalidade
  - Verificação da aderência dos protótipos às especificações de interface
  - Codificação da funcionalidade
  - Acompanhamento da aderência do código às regras do SONAR
=> Basis 219533 - Criar módulo de Material  de análise

chart/madre/templates/deployment.yaml, chart/madre/values.yaml, exames/src/main/docker/Dockerfile, seguranca/src/main/docker/Dockerfile
Nessa branch contém a inclusão dos módulos segurança e exames, onde foram realizadas alterações de configuração.
=> Adicionar os módulos segurança e exames no ambiente do Madre - BASIS-219724

exames/src/main/java/br/com/basis/madre/madreexames/MadreexamesApp.java, frontend/src/app/app.component.ts, frontend/src/app/exames/components/cadastrar-recipientes/cadastrar-recipientes.component.ts, frontend/src/app/exames/exames.routes.ts
=> Basis 226545
